/** these all are action types
  */
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT = 'LOGOUT';
export const STORE_VERIFICATION_DATA = 'STORE_VERIFICATION_DATA';

export const ADD_QUOTE = 'ADD_QUOTE';
export const CLEAR_QUOTES = 'CLEAR_QUOTES';

export const ADD_WORKOUT = 'ADD_WORKOUT';

export const SELECTED_USER = 'SELECTED_USER';
export const DELETE_SELECTED_USER = 'DELETE_SELECTED_USER';

export const SELECTED_GYM = 'SELECTED_GYM';
export const DELETE_SELECTED_GYM = 'DELETE_SELECTED_GYM';